<?php
if (!defined('WPINC')) { die(); }
define('MENSIO_PAGEINFO_DashBoard' , 'Welcome to Mensiopress. This is your dashboard.');
define('MENSIO_PAGEINFO_Catalogue' , 'Product catalogue maintenance.');
define('MENSIO_PAGEINFO_Brands' , 'Brands information management');
define('MENSIO_PAGEINFO_Categories' , 'Product categories definitions and attributes');
define('MENSIO_PAGEINFO_CategoriesTree' , 'Assign hierarchy to product categories');
define('MENSIO_PAGEINFO_Relations' , 'Product relations manager, useful for grouping products together, marketing-wise.');
define("MENSIO_PAGEINFO_Customers", 'Customer information management');
define("MENSIO_PAGEINFO_Deleted", 'This is the list of deleted customers');
define("MENSIO_PAGEINFO_MultiAccounts", 'Area for editing multi-account data');
define('MENSIO_PAGEINFO_Groups' , 'Define and populate customer groups');
define('MENSIO_PAGEINFO_Orders' , 'Orders management area');
define('MENSIO_PAGEINFO_Discounts' , 'Define and activate discount policies');
define('MENSIO_PAGEINFO_Tickets' , 'Flow and content of support requests from customers');
define('MENSIO_PAGEINFO_Marketing' , 'Marketing Page');
define('MENSIO_PAGEINFO_Coupons' , 'Define and activate discount coupons');
define('MENSIO_PAGEINFO_Reports' , 'Reports Page');
define('MENSIO_PAGEINFO_ReportsCommerce' , 'E-Commerce activity reporting options');
define('MENSIO_PAGEINFO_ReportsCustomers' , 'Customer activity reporting options');
define('MENSIO_PAGEINFO_ReportsActivity' , 'Website activity reporting options');
define('MENSIO_PAGEINFO_Design' , 'Area for including Mensiopress content blocks in pages');
define('MENSIO_PAGEINFO_Settings' , 'General store settings');
define('MENSIO_PAGEINFO_GlobalAttributes' , 'These product attributes are considered "Global", please select the type of value they should carry');
define('MENSIO_PAGEINFO_Shipping' , 'Define and manage the shipping methods and related costs');
define('MENSIO_PAGEINFO_Ratings' , 'Set the product rating type and advance method');
define('MENSIO_PAGEINFO_PaymentMethods' , 'Payment methods and gateways management');
define('MENSIO_PAGEINFO_UISettings' , 'Set default number of rows (in table mode) and alert timer option');
define('MENSIO_PAGEINFO_DefaultLanguages' , 'Set store default language options');
define('MENSIO_PAGEINFO_SalesSettings' , 'Set sales settings');
define('MENSIO_PAGEINFO_MailSettings' , 'Mail server settings and various mail templates');
define('MENSIO_PAGEINFO_UserPermissions' , 'Set store administrators user permissions');
define('MENSIO_PAGEINFO_TermsOfService' , 'Create and activate store "Terms Of Service" for customers to accept');
define('MENSIO_PAGEINFO_Continent' , 'Manage translation strings for continents');
define('MENSIO_PAGEINFO_Countries' , 'Manage countries data');
define('MENSIO_PAGEINFO_Currency' , 'Add or edit currency data');
define('MENSIO_PAGEINFO_Languages' , 'Select supported languages');
define('MENSIO_PAGEINFO_BusinessSectors' , 'Business sectors manage page');
define('MENSIO_PAGEINFO_Regions' , 'Define country regions  according to your needs');
define('MENSIO_PAGEINFO_System' , 'Systems Page');
define('MENSIO_PAGEINFO_SysHelp' , 'Help Page');
define('MENSIO_PAGEINFO_SysRegister' , 'Register Page');
define('MENSIO_PAGEINFO_SysStatus' , 'System and server status');
define('MENSIO_PAGEINFO_SysLogs' , 'Logs with system messages');
define('MENSIO_PAGEINFO_SysSupport' , 'Support Page');
define('MENSIO_PAGEINFO_SysBackup' , 'Backup Page');
define('MENSIO_PAGEINFO_SysAbout' , 'This is the Mensiopress "About" page. Thank you for your interest.');